export const tireColumns = [
  {
    name: "uid",
    label: "uid",
    field: "uid",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "description",
    label: "Description",
    field: "description",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "patternCode",
    label: "Pattern Code",
    field: "patternCode",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "type",
    label: "Type",
    field: "type",
    align: "left",
    sortable: false,
    headerStyle: "font-weight:bold",
  },
  {
    name: "category",
    label: "Category",
    field: "category",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "model",
    label: "Model",
    field: "model",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "brand",
    label: "Brand",
    field: "brand",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "totalQuantity",
    label: "Total Quantity",
    field: "totalQuantity",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "price",
    label: "Price",
    field: "price",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "agingPayable",
    label: "Aging Payable (Month)",
    field: "agingPayable",
    align: "left",
    sortable: false,
    headerStyle: "font-weight:bold",
  },
  {
    name: "created",
    label: "Created",
    field: "created",
    headerStyle: "font-weight:bold",
  },
  {
    name: "updated",
    label: "Updated",
    field: "updated",
    headerStyle: "font-weight:bold",
  },
  {
    name: "updatedBy",
    label: "Updated By",
    field: "updatedBy",
    headerStyle: "font-weight:bold",
  },
];

export const userColumns = [
  {
    name: "uid",
    label: "uid",
    field: "uid",
    classes: "hidden",
    headerClasses: "hidden",
  },
  {
    name: "firstName",
    label: "First Name",
    field: "firstName",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "lastName",
    label: "Last Name",
    field: "lastName",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "contact",
    label: "Contact",
    field: "contact",
    align: "left",
    sortable: false,
    headerStyle: "font-weight:bold",
  },
  {
    name: "address",
    label: "Address",
    field: "address",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "role",
    label: "Role",
    field: "role",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "email",
    label: "Email",
    field: "email",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "created",
    label: "Created At",
    field: "created",
    align: "left",
    format: (val) => {
      if (val) {
        let ret = new Date(val.toDate());
        return ret.toLocaleDateString() + ", " + ret.toLocaleTimeString();
      } else {
        return "";
      }
    },
    sortable: true,
    classes: "hidden",
    headerClasses: "hidden",
    headerStyle: "font-weight:bold",
  },
  {
    name: "updated",
    label: "Updated At",
    field: "updated",
    align: "left",
    format: (val) => {
      if (val) {
        let ret = new Date(val.toDate());
        return ret.toLocaleDateString() + ", " + ret.toLocaleTimeString();
      } else {
        return "";
      }
    },
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "updatedBy",
    label: "Updated By",
    field: "updatedBy",
    classes: "hidden",
    headerClasses: "hidden",
    headerStyle: "font-weight:bold",
  },
];

export const mtubeColumns = [
  {
    name: "uid",
    label: "uid",
    field: "uid",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "description",
    label: "Description",
    field: "description",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "sizes",
    label: "Sizes",
    field: "sizes",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "model",
    label: "Model",
    field: "model",
    align: "left",
    sortable: false,
    headerStyle: "font-weight:bold",
  },
  {
    name: "brand",
    label: "Brand",
    field: "brand",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "price",
    label: "Price",
    field: "price",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "agingPayable",
    label: "Aging Payable (Month)",
    field: "agingPayable",
    align: "left",
    sortable: false,
    headerStyle: "font-weight:bold",
  },
  {
    name: "created",
    label: "Created",
    field: "created",
    headerStyle: "font-weight:bold",
  },
  {
    name: "updated",
    label: "Updated",
    field: "updated",
    headerStyle: "font-weight:bold",
  },
  {
    name: "updatedBy",
    label: "Updated By",
    field: "updatedBy",
    headerStyle: "font-weight:bold",
  },
];

export const bikesColumns = [
  {
    name: "uid",
    label: "uid",
    field: "uid",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "description",
    label: "Description",
    field: "description",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "specs",
    label: "Specification",
    field: "specs",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "model",
    label: "Model",
    field: "model",
    align: "left",
    sortable: false,
    headerStyle: "font-weight:bold",
  },
  {
    name: "brand",
    label: "Brand",
    field: "brand",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "price",
    label: "Price",
    field: "price",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "agingPayable",
    label: "Aging Payable (Month)",
    field: "agingPayable",
    align: "left",
    sortable: false,
    headerStyle: "font-weight:bold",
  },
  {
    name: "created",
    label: "Created",
    field: "created",
    headerStyle: "font-weight:bold",
  },
  {
    name: "updated",
    label: "Updated",
    field: "updated",
    headerStyle: "font-weight:bold",
  },
  {
    name: "updatedBy",
    label: "Updated By",
    field: "updatedBy",
    headerStyle: "font-weight:bold",
  },
];

export const motorPartColumns = [
  {
    name: "uid",
    label: "uid",
    field: "uid",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "description",
    label: "Description",
    field: "description",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "model",
    label: "Model",
    field: "model",
    align: "left",
    sortable: false,
    headerStyle: "font-weight:bold",
  },
  {
    name: "brand",
    label: "Brand",
    field: "brand",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "price",
    label: "Price",
    field: "price",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "agingPayable",
    label: "Aging Payable (Month)",
    field: "agingPayable",
    align: "left",
    sortable: false,
    headerStyle: "font-weight:bold",
  },
  {
    name: "created",
    label: "Created",
    field: "created",
    headerStyle: "font-weight:bold",
  },
  {
    name: "updated",
    label: "Updated",
    field: "updated",
    headerStyle: "font-weight:bold",
  },
  {
    name: "updatedBy",
    label: "Updated By",
    field: "updatedBy",
    headerStyle: "font-weight:bold",
  },
];

export const stockInTireColumns = [
  {
    name: "uid",
    label: "uid",
    field: "uid",
  },
  {
    name: "itemId",
    label: "itemId",
    field: "itemId",
  },
  {
    name: "itemDesc",
    label: "Item Description",
    field: "itemDesc",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "itemType",
    label: "Item Type",
    field: "itemType",
    align: "left",
    sortable: false,
    headerStyle: "font-weight:bold",
  },
  {
    name: "itemPattern",
    label: "Pattern",
    field: "itemPattern",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "recentQty",
    label: "Recent QTY",
    field: "recentQty",
    align: "left",
    sortable: true,
    headerStyle: "font-weight:bold",
  },
  {
    name: "addedQty",
    label: "Added QTY",
    field: "addedQty",
    align: "left",
    sortable: false,
    headerStyle: "font-weight:bold",
  },
  {
    name: "totalQty",
    label: "Total QTY",
    field: "totalQty",
    align: "left",
    sortable: false,
    headerStyle: "font-weight:bold",
  },
  {
    name: "addedBy",
    label: "Added By",
    field: "addedBy",
    align: "left",
    headerStyle: "font-weight:bold",
  },
  {
    name: "created",
    label: "Created At",
    field: "created",
    headerStyle: "font-weight:bold",
    align: "left",
    // format: (val) => {
    //   if (val) {
    //     let ret = new Date(val.toDate());
    //     return ret.toLocaleDateString() + ", " + ret.toLocaleTimeString();
    //   } else {
    //     return "";
    //   }
    // },
  },
  {
    name: "deletedBy",
    label: "Deleted By",
    field: "deletedBy",
    align: "left",
    headerStyle: "font-weight:bold",
  },
  {
    name: "deleted",
    label: "Deleted At",
    field: "deleted",
    align: "left",
    headerStyle: "font-weight:bold",
  },
  {
    name: "action",
    label: "",
    field: "action",
    align: "left",
  },
];
